const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHAT";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

export {ALERT, REFETCH_CHATS, NEW_ATTACHMENT, NEW_MESSAGE_ALERT};